// Generated by graphics/build_mux.py. Edit that, not this.
window.ICONS = {
 "variants": [
  {
   "id": "classic",
   "title": "Classic",
   "claim": "Three models, an outlined body, one straight route to the card.",
   "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 256 256\" width=\"256\" height=\"256\">\n<title>InferMux</title>\n<path d=\"M84 36 L180 92 L180 164 L84 220 Z\" fill=\"%FILL%\" stroke=\"%EDGE%\" stroke-width=\"16\" stroke-linejoin=\"round\"/>\n<path d=\"M30 128 L84 128\" fill=\"none\" stroke=\"%IDLE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M30 184 L84 184\" fill=\"none\" stroke=\"%IDLE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M30 72 L160 128 L180 128 L226 128\" fill=\"none\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<circle cx=\"30\" cy=\"72\" r=\"18\" fill=\"%ACTIVE%\"/>\n<circle cx=\"30\" cy=\"128\" r=\"18\" fill=\"%IDLE%\"/>\n<circle cx=\"30\" cy=\"184\" r=\"18\" fill=\"%IDLE%\"/>\n<circle cx=\"226\" cy=\"128\" r=\"18\" fill=\"%ACTIVE%\"/>\n</svg>\n",
   "check": []
  },
  {
   "id": "four",
   "title": "Four inputs",
   "claim": "More models than one card holds. Lines only: four nodes do not fit a pixel apart in this body.",
   "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 256 256\" width=\"256\" height=\"256\">\n<title>InferMux</title>\n<path d=\"M84 36 L180 92 L180 164 L84 220 Z\" fill=\"%FILL%\" stroke=\"%EDGE%\" stroke-width=\"16\" stroke-linejoin=\"round\"/>\n<path d=\"M20 109.333 L84 109.333\" fill=\"none\" stroke=\"%IDLE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M20 146.667 L84 146.667\" fill=\"none\" stroke=\"%IDLE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M20 184 L84 184\" fill=\"none\" stroke=\"%IDLE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M20 72 L160 128 L180 128 L226 128\" fill=\"none\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<circle cx=\"226\" cy=\"128\" r=\"18\" fill=\"%ACTIVE%\"/>\n</svg>\n",
   "check": []
  },
  {
   "id": "solid",
   "title": "Solid body",
   "claim": "A filled grey body, the route on top. A heavier silhouette.",
   "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 256 256\" width=\"256\" height=\"256\">\n<title>InferMux</title>\n<path d=\"M84 36 L180 92 L180 164 L84 220 Z\" fill=\"%EDGE%\" stroke=\"%EDGE%\" stroke-width=\"16\" stroke-linejoin=\"round\"/>\n<path d=\"M30 128 L84 128\" fill=\"none\" stroke=\"%IDLE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M30 184 L84 184\" fill=\"none\" stroke=\"%IDLE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M30 72 L160 128 L180 128 L226 128\" fill=\"none\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<circle cx=\"30\" cy=\"72\" r=\"18\" fill=\"%ACTIVE%\"/>\n<circle cx=\"30\" cy=\"128\" r=\"18\" fill=\"%IDLE%\"/>\n<circle cx=\"30\" cy=\"184\" r=\"18\" fill=\"%IDLE%\"/>\n<circle cx=\"226\" cy=\"128\" r=\"18\" fill=\"%ACTIVE%\"/>\n</svg>\n",
   "check": []
  },
  {
   "id": "lines",
   "title": "No nodes",
   "claim": "Lines only on the input side.",
   "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 256 256\" width=\"256\" height=\"256\">\n<title>InferMux</title>\n<path d=\"M84 36 L180 92 L180 164 L84 220 Z\" fill=\"%FILL%\" stroke=\"%EDGE%\" stroke-width=\"16\" stroke-linejoin=\"round\"/>\n<path d=\"M20 128 L84 128\" fill=\"none\" stroke=\"%IDLE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M20 184 L84 184\" fill=\"none\" stroke=\"%IDLE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M20 72 L160 128 L180 128 L226 128\" fill=\"none\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<circle cx=\"226\" cy=\"128\" r=\"18\" fill=\"%ACTIVE%\"/>\n</svg>\n",
   "check": []
  },
  {
   "id": "vertical",
   "title": "Vertical",
   "claim": "Turned 90 degrees: models along the top, the card at the bottom.",
   "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 256 256\" width=\"256\" height=\"256\">\n<title>InferMux</title>\n<g transform=\"rotate(90 128 128)\">\n<path d=\"M84 36 L180 92 L180 164 L84 220 Z\" fill=\"%FILL%\" stroke=\"%EDGE%\" stroke-width=\"16\" stroke-linejoin=\"round\"/>\n<path d=\"M30 128 L84 128\" fill=\"none\" stroke=\"%IDLE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M30 184 L84 184\" fill=\"none\" stroke=\"%IDLE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M30 72 L160 128 L180 128 L226 128\" fill=\"none\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<circle cx=\"30\" cy=\"72\" r=\"18\" fill=\"%ACTIVE%\"/>\n<circle cx=\"30\" cy=\"128\" r=\"18\" fill=\"%IDLE%\"/>\n<circle cx=\"30\" cy=\"184\" r=\"18\" fill=\"%IDLE%\"/>\n<circle cx=\"226\" cy=\"128\" r=\"18\" fill=\"%ACTIVE%\"/>\n</g>\n</svg>\n",
   "check": []
  },
  {
   "id": "knockout",
   "title": "Knockout",
   "claim": "The body in the accent colour, the route cut out of it.",
   "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 256 256\" width=\"256\" height=\"256\">\n<title>InferMux</title>\n<mask id=\"cut\"><rect width=\"256\" height=\"256\" fill=\"#fff\"/><path d=\"M84 72 L160 128 L180 128\" fill=\"none\" stroke=\"#000\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></mask>\n<path d=\"M84 36 L180 92 L180 164 L84 220 Z\" fill=\"%ACTIVE%\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linejoin=\"round\" mask=\"url(#cut)\"/>\n<path d=\"M30 128 L84 128\" fill=\"none\" stroke=\"%IDLE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M30 184 L84 184\" fill=\"none\" stroke=\"%IDLE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M30 72 L84 72\" fill=\"none\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M180 128 L226 128\" fill=\"none\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<circle cx=\"30\" cy=\"72\" r=\"18\" fill=\"%ACTIVE%\"/>\n<circle cx=\"30\" cy=\"128\" r=\"18\" fill=\"%IDLE%\"/>\n<circle cx=\"30\" cy=\"184\" r=\"18\" fill=\"%IDLE%\"/>\n<circle cx=\"226\" cy=\"128\" r=\"18\" fill=\"%ACTIVE%\"/>\n</svg>\n",
   "check": []
  },
  {
   "id": "k-lines",
   "title": "Knockout, no nodes",
   "claim": "Lines only on the input side.",
   "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 256 256\" width=\"256\" height=\"256\">\n<title>InferMux</title>\n<mask id=\"cut\"><rect width=\"256\" height=\"256\" fill=\"#fff\"/><path d=\"M84 72 L160 128 L180 128\" fill=\"none\" stroke=\"#000\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></mask>\n<path d=\"M84 36 L180 92 L180 164 L84 220 Z\" fill=\"%ACTIVE%\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linejoin=\"round\" mask=\"url(#cut)\"/>\n<path d=\"M20 128 L84 128\" fill=\"none\" stroke=\"%IDLE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M20 184 L84 184\" fill=\"none\" stroke=\"%IDLE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M20 72 L84 72\" fill=\"none\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M180 128 L226 128\" fill=\"none\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<circle cx=\"226\" cy=\"128\" r=\"18\" fill=\"%ACTIVE%\"/>\n</svg>\n",
   "check": []
  },
  {
   "id": "k-four",
   "title": "Knockout, four inputs",
   "claim": "Four lines in, one cut through.",
   "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 256 256\" width=\"256\" height=\"256\">\n<title>InferMux</title>\n<mask id=\"cut\"><rect width=\"256\" height=\"256\" fill=\"#fff\"/><path d=\"M84 72 L160 128 L180 128\" fill=\"none\" stroke=\"#000\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></mask>\n<path d=\"M84 36 L180 92 L180 164 L84 220 Z\" fill=\"%ACTIVE%\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linejoin=\"round\" mask=\"url(#cut)\"/>\n<path d=\"M20 109.333 L84 109.333\" fill=\"none\" stroke=\"%IDLE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M20 146.667 L84 146.667\" fill=\"none\" stroke=\"%IDLE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M20 184 L84 184\" fill=\"none\" stroke=\"%IDLE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M20 72 L84 72\" fill=\"none\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M180 128 L226 128\" fill=\"none\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<circle cx=\"226\" cy=\"128\" r=\"18\" fill=\"%ACTIVE%\"/>\n</svg>\n",
   "check": []
  },
  {
   "id": "k-vertical",
   "title": "Knockout, vertical",
   "claim": "Models along the top, the card at the bottom.",
   "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 256 256\" width=\"256\" height=\"256\">\n<title>InferMux</title>\n<g transform=\"rotate(90 128 128)\">\n<mask id=\"cut\"><rect width=\"256\" height=\"256\" fill=\"#fff\"/><path d=\"M84 72 L160 128 L180 128\" fill=\"none\" stroke=\"#000\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></mask>\n<path d=\"M84 36 L180 92 L180 164 L84 220 Z\" fill=\"%ACTIVE%\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linejoin=\"round\" mask=\"url(#cut)\"/>\n<path d=\"M30 128 L84 128\" fill=\"none\" stroke=\"%IDLE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M30 184 L84 184\" fill=\"none\" stroke=\"%IDLE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M30 72 L84 72\" fill=\"none\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M180 128 L226 128\" fill=\"none\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<circle cx=\"30\" cy=\"72\" r=\"18\" fill=\"%ACTIVE%\"/>\n<circle cx=\"30\" cy=\"128\" r=\"18\" fill=\"%IDLE%\"/>\n<circle cx=\"30\" cy=\"184\" r=\"18\" fill=\"%IDLE%\"/>\n<circle cx=\"226\" cy=\"128\" r=\"18\" fill=\"%ACTIVE%\"/>\n</g>\n</svg>\n",
   "check": []
  },
  {
   "id": "k-notches",
   "title": "Knockout, dead ends",
   "claim": "The waiting models cut a short way into the body and stop. The chosen one cuts all the way through.",
   "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 256 256\" width=\"256\" height=\"256\">\n<title>InferMux</title>\n<mask id=\"cut\"><rect width=\"256\" height=\"256\" fill=\"#fff\"/><path d=\"M84 72 L160 128 L180 128\" fill=\"none\" stroke=\"#000\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M60 128 L104 128\" fill=\"none\" stroke=\"#000\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M60 184 L104 184\" fill=\"none\" stroke=\"#000\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></mask>\n<path d=\"M84 36 L180 92 L180 164 L84 220 Z\" fill=\"%ACTIVE%\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linejoin=\"round\" mask=\"url(#cut)\"/>\n<path d=\"M30 128 L84 128\" fill=\"none\" stroke=\"%IDLE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M30 184 L84 184\" fill=\"none\" stroke=\"%IDLE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M30 72 L84 72\" fill=\"none\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M180 128 L226 128\" fill=\"none\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<circle cx=\"30\" cy=\"72\" r=\"18\" fill=\"%ACTIVE%\"/>\n<circle cx=\"30\" cy=\"128\" r=\"18\" fill=\"%IDLE%\"/>\n<circle cx=\"30\" cy=\"184\" r=\"18\" fill=\"%IDLE%\"/>\n<circle cx=\"226\" cy=\"128\" r=\"18\" fill=\"%ACTIVE%\"/>\n</svg>\n",
   "check": []
  },
  {
   "id": "k-bare",
   "title": "Knockout, body only",
   "claim": "Nothing outside the body. The route is a cut from edge to edge: the fewest parts, the biggest at 16 px.",
   "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 256 256\" width=\"256\" height=\"256\">\n<title>InferMux</title>\n<mask id=\"cut\"><rect width=\"256\" height=\"256\" fill=\"#fff\"/><path d=\"M60 72 L84 72 L160 128 L204 128\" fill=\"none\" stroke=\"#000\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></mask>\n<path d=\"M84 36 L180 92 L180 164 L84 220 Z\" fill=\"%ACTIVE%\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linejoin=\"round\" mask=\"url(#cut)\"/>\n</svg>\n",
   "check": []
  },
  {
   "id": "k-bare-notches",
   "title": "Knockout, body only, dead ends",
   "claim": "Body only, with the waiting models as short cuts that stop. The cut runs parallel to the top edge. The chosen mark.",
   "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"22 18 220 220\" width=\"256\" height=\"256\">\n<title>InferMux</title>\n<mask id=\"cut\"><rect width=\"256\" height=\"256\" fill=\"#fff\"/><path d=\"M60 72 L84 72 L180 128 L204 128\" fill=\"none\" stroke=\"#000\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M60 128 L104 128\" fill=\"none\" stroke=\"#000\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M60 184 L104 184\" fill=\"none\" stroke=\"#000\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></mask>\n<path d=\"M84 36 L180 92 L180 164 L84 220 Z\" fill=\"%ACTIVE%\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linejoin=\"round\" mask=\"url(#cut)\"/>\n</svg>\n",
   "check": []
  },
  {
   "id": "k-inlay",
   "title": "Knockout, inlaid route",
   "claim": "A wide cut with the route drawn inside it, so the route keeps the accent colour and still reads as a cut.",
   "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 256 256\" width=\"256\" height=\"256\">\n<title>InferMux</title>\n<mask id=\"cut\"><rect width=\"256\" height=\"256\" fill=\"#fff\"/><path d=\"M84 72 L160 128 L180 128\" fill=\"none\" stroke=\"#000\" stroke-width=\"48\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></mask>\n<path d=\"M84 36 L180 92 L180 164 L84 220 Z\" fill=\"%ACTIVE%\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linejoin=\"round\" mask=\"url(#cut)\"/>\n<path d=\"M30 128 L84 128\" fill=\"none\" stroke=\"%IDLE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M30 184 L84 184\" fill=\"none\" stroke=\"%IDLE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M30 72 L160 128 L180 128 L226 128\" fill=\"none\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<circle cx=\"30\" cy=\"72\" r=\"18\" fill=\"%ACTIVE%\"/>\n<circle cx=\"30\" cy=\"128\" r=\"18\" fill=\"%IDLE%\"/>\n<circle cx=\"30\" cy=\"184\" r=\"18\" fill=\"%IDLE%\"/>\n<circle cx=\"226\" cy=\"128\" r=\"18\" fill=\"%ACTIVE%\"/>\n</svg>\n",
   "check": []
  },
  {
   "id": "k-inlay-bare",
   "title": "Knockout, inlaid, body only",
   "claim": "The inlaid route with nothing outside the body.",
   "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 256 256\" width=\"256\" height=\"256\">\n<title>InferMux</title>\n<mask id=\"cut\"><rect width=\"256\" height=\"256\" fill=\"#fff\"/><path d=\"M60 72 L84 72 L160 128 L204 128\" fill=\"none\" stroke=\"#000\" stroke-width=\"48\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></mask>\n<path d=\"M84 36 L180 92 L180 164 L84 220 Z\" fill=\"%ACTIVE%\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linejoin=\"round\" mask=\"url(#cut)\"/>\n<path d=\"M160 128 L180 128\" fill=\"none\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n</svg>\n",
   "check": []
  },
  {
   "id": "k-mono",
   "title": "Knockout, one colour",
   "claim": "Everything in the accent. The waiting models are told apart by stopping at the body; the chosen one cuts through.",
   "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 256 256\" width=\"256\" height=\"256\">\n<title>InferMux</title>\n<mask id=\"cut\"><rect width=\"256\" height=\"256\" fill=\"#fff\"/><path d=\"M84 72 L160 128 L180 128\" fill=\"none\" stroke=\"#000\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></mask>\n<path d=\"M84 36 L180 92 L180 164 L84 220 Z\" fill=\"%ACTIVE%\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linejoin=\"round\" mask=\"url(#cut)\"/>\n<path d=\"M30 128 L84 128\" fill=\"none\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M30 184 L84 184\" fill=\"none\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M30 72 L84 72\" fill=\"none\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M180 128 L226 128\" fill=\"none\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<circle cx=\"30\" cy=\"72\" r=\"18\" fill=\"%ACTIVE%\"/>\n<circle cx=\"30\" cy=\"128\" r=\"18\" fill=\"%ACTIVE%\"/>\n<circle cx=\"30\" cy=\"184\" r=\"18\" fill=\"%ACTIVE%\"/>\n<circle cx=\"226\" cy=\"128\" r=\"18\" fill=\"%ACTIVE%\"/>\n</svg>\n",
   "check": []
  },
  {
   "id": "k-mono-notches",
   "title": "Knockout, one colour, dead ends",
   "claim": "One colour, and the waiting models also cut a short way in and stop.",
   "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 256 256\" width=\"256\" height=\"256\">\n<title>InferMux</title>\n<mask id=\"cut\"><rect width=\"256\" height=\"256\" fill=\"#fff\"/><path d=\"M84 72 L160 128 L180 128\" fill=\"none\" stroke=\"#000\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M60 128 L104 128\" fill=\"none\" stroke=\"#000\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M60 184 L104 184\" fill=\"none\" stroke=\"#000\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></mask>\n<path d=\"M84 36 L180 92 L180 164 L84 220 Z\" fill=\"%ACTIVE%\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linejoin=\"round\" mask=\"url(#cut)\"/>\n<path d=\"M30 128 L84 128\" fill=\"none\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M30 184 L84 184\" fill=\"none\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M30 72 L84 72\" fill=\"none\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M180 128 L226 128\" fill=\"none\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<circle cx=\"30\" cy=\"72\" r=\"18\" fill=\"%ACTIVE%\"/>\n<circle cx=\"30\" cy=\"128\" r=\"18\" fill=\"%ACTIVE%\"/>\n<circle cx=\"30\" cy=\"184\" r=\"18\" fill=\"%ACTIVE%\"/>\n<circle cx=\"226\" cy=\"128\" r=\"18\" fill=\"%ACTIVE%\"/>\n</svg>\n",
   "check": []
  },
  {
   "id": "k-mono-lines",
   "title": "Knockout, one colour, no nodes",
   "claim": "One colour, lines only on the input side.",
   "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 256 256\" width=\"256\" height=\"256\">\n<title>InferMux</title>\n<mask id=\"cut\"><rect width=\"256\" height=\"256\" fill=\"#fff\"/><path d=\"M84 72 L160 128 L180 128\" fill=\"none\" stroke=\"#000\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></mask>\n<path d=\"M84 36 L180 92 L180 164 L84 220 Z\" fill=\"%ACTIVE%\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linejoin=\"round\" mask=\"url(#cut)\"/>\n<path d=\"M20 128 L84 128\" fill=\"none\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M20 184 L84 184\" fill=\"none\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M20 72 L84 72\" fill=\"none\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M180 128 L226 128\" fill=\"none\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<circle cx=\"226\" cy=\"128\" r=\"18\" fill=\"%ACTIVE%\"/>\n</svg>\n",
   "check": []
  },
  {
   "id": "k-tonal",
   "title": "Knockout, tonal",
   "claim": "The waiting models in the accent at 40%, so the icon is one hue.",
   "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 256 256\" width=\"256\" height=\"256\">\n<title>InferMux</title>\n<mask id=\"cut\"><rect width=\"256\" height=\"256\" fill=\"#fff\"/><path d=\"M84 72 L160 128 L180 128\" fill=\"none\" stroke=\"#000\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></mask>\n<path d=\"M84 36 L180 92 L180 164 L84 220 Z\" fill=\"%ACTIVE%\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linejoin=\"round\" mask=\"url(#cut)\"/>\n<path d=\"M30 128 L84 128\" fill=\"none\" stroke=\"%ACTIVE%\" stroke-opacity=\"0.4\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M30 184 L84 184\" fill=\"none\" stroke=\"%ACTIVE%\" stroke-opacity=\"0.4\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M30 72 L84 72\" fill=\"none\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M180 128 L226 128\" fill=\"none\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<circle cx=\"30\" cy=\"72\" r=\"18\" fill=\"%ACTIVE%\"/>\n<circle cx=\"30\" cy=\"128\" r=\"18\" fill=\"%ACTIVE%\" fill-opacity=\"0.4\"/>\n<circle cx=\"30\" cy=\"184\" r=\"18\" fill=\"%ACTIVE%\" fill-opacity=\"0.4\"/>\n<circle cx=\"226\" cy=\"128\" r=\"18\" fill=\"%ACTIVE%\"/>\n</svg>\n",
   "check": []
  },
  {
   "id": "k-tonal-notches",
   "title": "Knockout, tonal, dead ends",
   "claim": "Tonal, with the dead-end cuts.",
   "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 256 256\" width=\"256\" height=\"256\">\n<title>InferMux</title>\n<mask id=\"cut\"><rect width=\"256\" height=\"256\" fill=\"#fff\"/><path d=\"M84 72 L160 128 L180 128\" fill=\"none\" stroke=\"#000\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M60 128 L104 128\" fill=\"none\" stroke=\"#000\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M60 184 L104 184\" fill=\"none\" stroke=\"#000\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></mask>\n<path d=\"M84 36 L180 92 L180 164 L84 220 Z\" fill=\"%ACTIVE%\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linejoin=\"round\" mask=\"url(#cut)\"/>\n<path d=\"M30 128 L84 128\" fill=\"none\" stroke=\"%ACTIVE%\" stroke-opacity=\"0.4\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M30 184 L84 184\" fill=\"none\" stroke=\"%ACTIVE%\" stroke-opacity=\"0.4\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M30 72 L84 72\" fill=\"none\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M180 128 L226 128\" fill=\"none\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<circle cx=\"30\" cy=\"72\" r=\"18\" fill=\"%ACTIVE%\"/>\n<circle cx=\"30\" cy=\"128\" r=\"18\" fill=\"%ACTIVE%\" fill-opacity=\"0.4\"/>\n<circle cx=\"30\" cy=\"184\" r=\"18\" fill=\"%ACTIVE%\" fill-opacity=\"0.4\"/>\n<circle cx=\"226\" cy=\"128\" r=\"18\" fill=\"%ACTIVE%\"/>\n</svg>\n",
   "check": []
  },
  {
   "id": "k-open",
   "title": "Knockout, open output",
   "claim": "No card node: the cut runs out of the body's right edge.",
   "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 256 256\" width=\"256\" height=\"256\">\n<title>InferMux</title>\n<mask id=\"cut\"><rect width=\"256\" height=\"256\" fill=\"#fff\"/><path d=\"M84 72 L160 128 L204 128\" fill=\"none\" stroke=\"#000\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></mask>\n<path d=\"M84 36 L180 92 L180 164 L84 220 Z\" fill=\"%ACTIVE%\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linejoin=\"round\" mask=\"url(#cut)\"/>\n<path d=\"M30 128 L84 128\" fill=\"none\" stroke=\"%IDLE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M30 184 L84 184\" fill=\"none\" stroke=\"%IDLE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M30 72 L84 72\" fill=\"none\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<circle cx=\"30\" cy=\"72\" r=\"18\" fill=\"%ACTIVE%\"/>\n<circle cx=\"30\" cy=\"128\" r=\"18\" fill=\"%IDLE%\"/>\n<circle cx=\"30\" cy=\"184\" r=\"18\" fill=\"%IDLE%\"/>\n</svg>\n",
   "check": []
  },
  {
   "id": "k-mono-open",
   "title": "Knockout, one colour, open output",
   "claim": "One colour, and the cut runs out of the right edge.",
   "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 256 256\" width=\"256\" height=\"256\">\n<title>InferMux</title>\n<mask id=\"cut\"><rect width=\"256\" height=\"256\" fill=\"#fff\"/><path d=\"M84 72 L160 128 L204 128\" fill=\"none\" stroke=\"#000\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></mask>\n<path d=\"M84 36 L180 92 L180 164 L84 220 Z\" fill=\"%ACTIVE%\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linejoin=\"round\" mask=\"url(#cut)\"/>\n<path d=\"M30 128 L84 128\" fill=\"none\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M30 184 L84 184\" fill=\"none\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M30 72 L84 72\" fill=\"none\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<circle cx=\"30\" cy=\"72\" r=\"18\" fill=\"%ACTIVE%\"/>\n<circle cx=\"30\" cy=\"128\" r=\"18\" fill=\"%ACTIVE%\"/>\n<circle cx=\"30\" cy=\"184\" r=\"18\" fill=\"%ACTIVE%\"/>\n</svg>\n",
   "check": []
  },
  {
   "id": "engraved",
   "title": "Engraved",
   "claim": "An accent body with the route drawn dark on it instead of cut. Differs from the knockout only where the background is not dark: a tile, or white.",
   "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 256 256\" width=\"256\" height=\"256\">\n<title>InferMux</title>\n<path d=\"M84 36 L180 92 L180 164 L84 220 Z\" fill=\"%ACTIVE%\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linejoin=\"round\"/>\n<path d=\"M30 128 L84 128\" fill=\"none\" stroke=\"%IDLE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M30 184 L84 184\" fill=\"none\" stroke=\"%IDLE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M30 72 L84 72\" fill=\"none\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M160 128 L180 128\" fill=\"none\" stroke=\"%FILL%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M180 128 L226 128\" fill=\"none\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<circle cx=\"30\" cy=\"72\" r=\"18\" fill=\"%ACTIVE%\"/>\n<circle cx=\"30\" cy=\"128\" r=\"18\" fill=\"%IDLE%\"/>\n<circle cx=\"30\" cy=\"184\" r=\"18\" fill=\"%IDLE%\"/>\n<circle cx=\"226\" cy=\"128\" r=\"18\" fill=\"%ACTIVE%\"/>\n</svg>\n",
   "check": []
  },
  {
   "id": "accent-outline",
   "title": "Accent outline",
   "claim": "The classic, with the body's outline in the accent instead of grey.",
   "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 256 256\" width=\"256\" height=\"256\">\n<title>InferMux</title>\n<path d=\"M84 36 L180 92 L180 164 L84 220 Z\" fill=\"%FILL%\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linejoin=\"round\"/>\n<path d=\"M30 128 L84 128\" fill=\"none\" stroke=\"%IDLE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M30 184 L84 184\" fill=\"none\" stroke=\"%IDLE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M30 72 L160 128 L180 128 L226 128\" fill=\"none\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<circle cx=\"30\" cy=\"72\" r=\"18\" fill=\"%ACTIVE%\"/>\n<circle cx=\"30\" cy=\"128\" r=\"18\" fill=\"%IDLE%\"/>\n<circle cx=\"30\" cy=\"184\" r=\"18\" fill=\"%IDLE%\"/>\n<circle cx=\"226\" cy=\"128\" r=\"18\" fill=\"%ACTIVE%\"/>\n</svg>\n",
   "check": []
  },
  {
   "id": "accent-outline-tonal",
   "title": "Accent outline, tonal",
   "claim": "Accent outline, the waiting models at 40%.",
   "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 256 256\" width=\"256\" height=\"256\">\n<title>InferMux</title>\n<path d=\"M84 36 L180 92 L180 164 L84 220 Z\" fill=\"%FILL%\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linejoin=\"round\"/>\n<path d=\"M30 128 L84 128\" fill=\"none\" stroke=\"%ACTIVE%\" stroke-opacity=\"0.4\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M30 184 L84 184\" fill=\"none\" stroke=\"%ACTIVE%\" stroke-opacity=\"0.4\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M30 72 L160 128 L180 128 L226 128\" fill=\"none\" stroke=\"%ACTIVE%\" stroke-width=\"16\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<circle cx=\"30\" cy=\"72\" r=\"18\" fill=\"%ACTIVE%\"/>\n<circle cx=\"30\" cy=\"128\" r=\"18\" fill=\"%ACTIVE%\" fill-opacity=\"0.4\"/>\n<circle cx=\"30\" cy=\"184\" r=\"18\" fill=\"%ACTIVE%\" fill-opacity=\"0.4\"/>\n<circle cx=\"226\" cy=\"128\" r=\"18\" fill=\"%ACTIVE%\"/>\n</svg>\n",
   "check": []
  }
 ],
 "palettes": [
  {
   "idle": "#6B7178",
   "edge": "#8A929B",
   "fill": "#1E2226",
   "id": "sky",
   "title": "sky (the UI's accent)",
   "active": "#38BDF8"
  },
  {
   "idle": "#6B7178",
   "edge": "#8A929B",
   "fill": "#1E2226",
   "id": "blue",
   "title": "blue",
   "active": "#5B8CFF"
  },
  {
   "idle": "#6B7178",
   "edge": "#8A929B",
   "fill": "#1E2226",
   "id": "violet",
   "title": "violet",
   "active": "#A78BFA"
  },
  {
   "idle": "#6B7178",
   "edge": "#8A929B",
   "fill": "#1E2226",
   "id": "fuchsia",
   "title": "fuchsia",
   "active": "#E879F9"
  },
  {
   "idle": "#6B7178",
   "edge": "#8A929B",
   "fill": "#1E2226",
   "id": "white",
   "title": "white",
   "active": "#E8ECF0"
  },
  {
   "idle": "#6B7178",
   "edge": "#8A929B",
   "fill": "#1E2226",
   "id": "green",
   "title": "green (Episteme's)",
   "active": "#17D98E"
  },
  {
   "idle": "#6B7178",
   "edge": "#8A929B",
   "fill": "#1E2226",
   "id": "amber",
   "title": "amber (the UI's pause)",
   "active": "#FBBF24"
  }
 ]
};
